services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_usuarios'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3306'